

# ----------------------------------------------------------------------------------------
set(RESINSIGHT_FWK_VIZFWK_LIBRENDER 
	"${PROJECT_SOURCE_DIR}/resinsight/Fwk/VizFwk/LibRender/")

set(LIBRENDER_SOURCE
	${RESINSIGHT_FWK_VIZFWK_LIBRENDER}cvfGeometryBuilderDrawableGeo.cpp
	# ${RESINSIGHT_FWK_VIZFWK_LIBRENDER}cvfPrimitiveSetIndexedUInt.cpp
	${RESINSIGHT_FWK_VIZFWK_LIBRENDER}cvfScalarMapper.cpp
	# ${RESINSIGHT_FWK_VIZFWK_LIBRENDER}cvfOutlineEdgeExtractor.cpp
	# ${RESINSIGHT_FWK_VIZFWK_LIBRENDER}cvfDrawableGeo.cpp
	${RESINSIGHT_FWK_VIZFWK_LIBRENDER}cvfDrawable.cpp
	${RESINSIGHT_FWK_VIZFWK_LIBRENDER}cvfHitDetail.cpp
	# ${RESINSIGHT_FWK_VIZFWK_LIBRENDER}cvfPrimitiveSet.cpp
)

set(LIBRENDER_HEADERS
	${RESINSIGHT_FWK_VIZFWK_LIBRENDER}cvfGeometryBuilderDrawableGeo.h
	# ${RESINSIGHT_FWK_VIZFWK_LIBRENDER}cvfPrimitiveSetIndexedUInt.h
	${RESINSIGHT_FWK_VIZFWK_LIBRENDER}cvfScalarMapper.h
	# ${RESINSIGHT_FWK_VIZFWK_LIBRENDER}cvfOutlineEdgeExtractor.h
	# ${RESINSIGHT_FWK_VIZFWK_LIBRENDER}cvfDrawableGeo.h
	${RESINSIGHT_FWK_VIZFWK_LIBRENDER}cvfDrawable.h
	${RESINSIGHT_FWK_VIZFWK_LIBRENDER}cvfHitDetail.h
	# ${RESINSIGHT_FWK_VIZFWK_LIBRENDER}cvfPrimitiveSet.h
	# ${RESINSIGHT_FWK_VIZFWK_LIBRENDER}cvfOpenGLTypes.h
)

# ----------------------------------------------------------------------------------------
set(RESINSIGHT_FWK_VIZFWK_LIBCORE 
	"${PROJECT_SOURCE_DIR}/resinsight/Fwk/VizFwk/LibCore/")

set(LIBCORE_SOURCE
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfVector2.cpp
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfVector3.cpp
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfVector4.cpp
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfVector2.inl
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfVector3.inl
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfVector4.inl
#
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfObject.cpp
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfObject.inl
# 
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfMatrix3.inl
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfMatrix4.inl
#
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfCollection.inl
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfArray.inl
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfString.cpp
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfSystem.cpp
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfCharArray.cpp
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfColor3.cpp
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfAssert.cpp
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfAtomicCounter.cpp
# ${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfDebugTimer.cpp
# ${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfTimer.cpp
# ${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfBase64.cpp
# ${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfLogger.cpp
# ${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfCodeLocation.cpp
# ${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfLogEvent.cpp
# ${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfTBBControl.cpp
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfTrace.cpp
# ${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfMath.inl
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfMath.cpp
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfPlane.cpp
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfFlags.inl
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfRect.inl
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfQuat.inl
)

set(LIBCORE_HEADERS
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfVector3.h
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfVector4.h
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfVersion.h
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfPlane.h
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfString.h
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfSystem.h
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfValueArray.h
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfVector2.h
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfBase.h
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfCharArray.h
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfCollection.h
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfColor3.h
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfColor4.h
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfConfigCore.h
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfMath.h
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfMatrix3.h
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfMatrix4.h
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfObject.h
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfArray.h
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfArrayWrapperConst.h
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfAssert.h
# ${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfAtomicCounter.h
# ${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfTimer.h
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfLibCore.h
# ${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfBase64.h
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfFlags.h
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfFunctorRange.h
# ${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfLogger.h
# ${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfCodeLocation.h
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfLogDestination.h
# ${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfLogEvent.h
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfRect.h
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfQuat.h
# ${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfTBBControl.h
${RESINSIGHT_FWK_VIZFWK_LIBCORE}cvfTrace.h
)

# ----------------------------------------------------------------------------------------
set(RESINSIGHT_FWK_VIZFWK_LIBGEOMETRY 
	"${PROJECT_SOURCE_DIR}/resinsight/Fwk/VizFwk/LibGeometry/")

set(LIBGEOMETRY_SOURCE
${RESINSIGHT_FWK_VIZFWK_LIBGEOMETRY}cvfBoundingBox.cpp
${RESINSIGHT_FWK_VIZFWK_LIBGEOMETRY}cvfGeometryBuilder.cpp
${RESINSIGHT_FWK_VIZFWK_LIBGEOMETRY}cvfOutlineEdgeExtractor.cpp
${RESINSIGHT_FWK_VIZFWK_LIBGEOMETRY}cvfEdgeKey.cpp
${RESINSIGHT_FWK_VIZFWK_LIBGEOMETRY}cvfGeometryUtils.cpp
${RESINSIGHT_FWK_VIZFWK_LIBGEOMETRY}cvfBoundingBoxTree.cpp
${RESINSIGHT_FWK_VIZFWK_LIBGEOMETRY}cvfRay.cpp
)

set(LIBGEOMETRY_HEADERS
${RESINSIGHT_FWK_VIZFWK_LIBGEOMETRY}cvfBoundingBox.h
${RESINSIGHT_FWK_VIZFWK_LIBGEOMETRY}cvfGeometryBuilder.h
${RESINSIGHT_FWK_VIZFWK_LIBGEOMETRY}cvfOutlineEdgeExtractor.h
${RESINSIGHT_FWK_VIZFWK_LIBGEOMETRY}cvfEdgeKey.h
${RESINSIGHT_FWK_VIZFWK_LIBGEOMETRY}cvfGeometryUtils.h
${RESINSIGHT_FWK_VIZFWK_LIBGEOMETRY}cvfBoundingBoxTree.h
${RESINSIGHT_FWK_VIZFWK_LIBGEOMETRY}cvfRay.h
)

# ----------------------------------------------------------------------------------------
set(RESINSIGHT_FWK_APPFWK_CAFPROJECTDATAMODEL 
	"${PROJECT_SOURCE_DIR}/resinsight/Fwk/AppFwk/cafProjectDataModel/")

set(CAFPROJECTDATAMODEL_HEADERS
${RESINSIGHT_FWK_APPFWK_CAFPROJECTDATAMODEL}cafFixedArray.h
${RESINSIGHT_FWK_APPFWK_CAFPROJECTDATAMODEL}cafPdmField.h
)

# ----------------------------------------------------------------------------------------
set(RESINSIGHT_FWK_APPFWK_CAFPROJECTDATAMODEL_CAFPDMCORE 
	"${PROJECT_SOURCE_DIR}/resinsight/Fwk/AppFwk/cafProjectDataModel/cafPdmCore/")

set(CAFPDMCORE_SOURCE
# ${RESINSIGHT_FWK_APPFWK_CAFPROJECTDATAMODEL_CAFPDMCORE}cafPdmObjectHandle.cpp
)

set(CAFPDMCORE_HEADERS
# ${RESINSIGHT_FWK_APPFWK_CAFPROJECTDATAMODEL_CAFPDMCORE}cafAppEnum.h
${RESINSIGHT_FWK_APPFWK_CAFPROJECTDATAMODEL_CAFPDMCORE}cafAssert.h
# ${RESINSIGHT_FWK_APPFWK_CAFPROJECTDATAMODEL_CAFPDMCORE}cafPdmObjectHandle.h
)

# ----------------------------------------------------------------------------------------
set(RESINSIGHT_FWK_APPFWK_CAFVIZEXTENSIONS 
	"${PROJECT_SOURCE_DIR}/resinsight/Fwk/AppFwk/cafVizExtensions/")

# ----------------------------------------------------------------------------------------
set(RESINSIGHT_FWK_APPFWK_CAFVIZEXTENSIONS_CAFHEXGRIDINTERSECTIONTOOLS 
	"${PROJECT_SOURCE_DIR}/resinsight/Fwk/AppFwk/cafVizExtensions/cafHexGridIntersectionTools/")

set(CAFHEXGRIDINTERSECTIONTOOLS_HEADERS
${RESINSIGHT_FWK_APPFWK_CAFVIZEXTENSIONS_CAFHEXGRIDINTERSECTIONTOOLS}cafHexGridIntersectionTools.h
)

set(CAFHEXGRIDINTERSECTIONTOOLS_SOURCE
${RESINSIGHT_FWK_APPFWK_CAFVIZEXTENSIONS_CAFHEXGRIDINTERSECTIONTOOLS}cafHexGridIntersectionTools.cpp
)

# ----------------------------------------------------------------------------------------
set(RESINSIGHT_FWK_APPFWK_COMMONCODE 
	"${PROJECT_SOURCE_DIR}/resinsight/Fwk/AppFwk/CommonCode/")

set(COMMONCODE_SOURCE
${RESINSIGHT_FWK_APPFWK_COMMONCODE}cvfStructGridGeometryGenerator.cpp
${RESINSIGHT_FWK_APPFWK_COMMONCODE}cvfCellRange.cpp
${RESINSIGHT_FWK_APPFWK_COMMONCODE}cvfStructGrid.cpp
${RESINSIGHT_FWK_APPFWK_COMMONCODE}cafUtils.cpp
)

set(COMMONCODE_HEADERS	
${RESINSIGHT_FWK_APPFWK_COMMONCODE}cvfStructGridGeometryGenerator.h
${RESINSIGHT_FWK_APPFWK_COMMONCODE}cvfCellRange.h
${RESINSIGHT_FWK_APPFWK_COMMONCODE}cvfStructGrid.h
${RESINSIGHT_FWK_APPFWK_COMMONCODE}cafUtils.h
)

# ----------------------------------------------------------------------------------------
set(RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL 
	"${PROJECT_SOURCE_DIR}/resinsight/ApplicationCode/ReservoirDataModel/")

set(RESERVOIRDATAMODEL_SOURCE
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigLocalGrid.cpp
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}cvfGeometryTools.cpp
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigMainGrid.cpp
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigWellPath.cpp
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigNNCData.cpp
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigWellPathIntersectionTools.cpp
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigCell.cpp
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigHexIntersectionTools.cpp
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigFault.cpp
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigGridBase.cpp
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigActiveCellInfo.cpp
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigCellGeometryTools.cpp
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigEclipseCaseData.cpp
# ${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigEclipseWellLogExtractor.cpp
# ${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigSimulationWellCenterLineCalculator.cpp
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigCaseCellResultsData.cpp
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigSimWellData.cpp
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigEclipseResultInfo.cpp
)

set(RESERVOIRDATAMODEL_HEADERS
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}cvfGeometryTools.h
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}cvfGeometryTools.inl
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigWellPath.h
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigWellPathIntersectionTools.h
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigGridBase.h
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigHexIntersectionTools.h
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigLocalGrid.h
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigMainGrid.h
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigNNCData.h
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigCell.h
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigFault.h
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigActiveCellInfo.h
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigWellLogExtractionTools.h
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigCellGeometryTools.h
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigEclipseCaseData.h
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigEclipseWellLogExtractor.h
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigSimulationWellCoordsAndMD.cpp
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigSimulationWellCoordsAndMD.h
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigCaseCellResultsData.h
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigSimWellData.h
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigSimulationWellCenterLineCalculator.h
${RESINSIGHT_APPLICATIONCODE_RESERVOIRDATAMODEL}RigEclipseResultInfo.h
)

# ----------------------------------------------------------------------------------------
set(RESINSIGHT_APPLICATIONCODE_APPLICATION 
	"${PROJECT_SOURCE_DIR}/resinsight/ApplicationCode/Application/")

set(APPLICATION_SOURCE
${RESINSIGHT_APPLICATIONCODE_APPLICATION}RiaDefines.cpp
${RESINSIGHT_APPLICATIONCODE_APPLICATION}RiaPorosityModel.cpp
# ${RESINSIGHT_APPLICATIONCODE_APPLICATION}RiaApplication.cpp
# ${RESINSIGHT_APPLICATIONCODE_APPLICATION}RiaPreferences.cpp
)

set(APPLICATION_HEADERS
${RESINSIGHT_APPLICATIONCODE_APPLICATION}RiaDefines.h
${RESINSIGHT_APPLICATIONCODE_APPLICATION}RiaPorosityModel.h
# ${RESINSIGHT_APPLICATIONCODE_APPLICATION}RiaApplication.h
# ${RESINSIGHT_APPLICATIONCODE_APPLICATION}RiaPreferences.h
)

# ----------------------------------------------------------------------------------------
set(RESINSIGHT_APPLICATIONCODE_APPLICATION_TOOLS 
	"${PROJECT_SOURCE_DIR}/resinsight/ApplicationCode/Application/Tools/")

set(APPLICATION_TOOLS_SOURCE
${RESINSIGHT_APPLICATIONCODE_APPLICATION_TOOLS}RiaQDateTimeTools.cpp
# ${RESINSIGHT_APPLICATIONCODE_APPLICATION_TOOLS}RiaLogging.cpp
)

set(APPLICATION_TOOLS_HEADERS
${RESINSIGHT_APPLICATIONCODE_APPLICATION_TOOLS}RiaQDateTimeTools.h
# ${RESINSIGHT_APPLICATIONCODE_APPLICATION_TOOLS}RiaLogging.h
)

# ----------------------------------------------------------------------------------------
set(RESINSIGHT_APPLICATIONCODE_FILEINTERFACE 
	"${PROJECT_SOURCE_DIR}/resinsight/ApplicationCode/FileInterface/")

set(APPLICATIONCODE_FILEINTERFACE_SOURCE
${RESINSIGHT_APPLICATIONCODE_FILEINTERFACE}RifEclipseOutputFileTools.cpp
${RESINSIGHT_APPLICATIONCODE_FILEINTERFACE}RifEclipseRestartDataAccess.cpp
${RESINSIGHT_APPLICATIONCODE_FILEINTERFACE}RifEclipseRestartFilesetAccess.cpp
${RESINSIGHT_APPLICATIONCODE_FILEINTERFACE}RifReaderInterface.cpp
${RESINSIGHT_APPLICATIONCODE_FILEINTERFACE}RifEclipseUnifiedRestartFileAccess.cpp
${RESINSIGHT_APPLICATIONCODE_FILEINTERFACE}RifReaderEclipseOutput.cpp
${RESINSIGHT_APPLICATIONCODE_FILEINTERFACE}RifEclipseInputFileTools.cpp
# ${RESINSIGHT_APPLICATIONCODE_FILEINTERFACE}RifReaderSettings.cpp
)

set(APPLICATIONCODE_FILEINTERFACE_HEADERS
${RESINSIGHT_APPLICATIONCODE_FILEINTERFACE}RifEclipseRestartDataAccess.h
${RESINSIGHT_APPLICATIONCODE_FILEINTERFACE}RifEclipseRestartDataAccess.cpp
${RESINSIGHT_APPLICATIONCODE_FILEINTERFACE}RifEclipseRestartFilesetAccess.h
${RESINSIGHT_APPLICATIONCODE_FILEINTERFACE}RifReaderInterface.h
${RESINSIGHT_APPLICATIONCODE_FILEINTERFACE}RifEclipseUnifiedRestartFileAccess.h
${RESINSIGHT_APPLICATIONCODE_FILEINTERFACE}RifReaderEclipseOutput.h
${RESINSIGHT_APPLICATIONCODE_FILEINTERFACE}RifEclipseInputFileTools.h
# ${RESINSIGHT_APPLICATIONCODE_FILEINTERFACE}RifReaderSettings.h
)

# ----------------------------------------------------------------------------------------
set(RESINSIGHT_APPLICATIONCODE_PROJECTDATAMODEL 
	"${PROJECT_SOURCE_DIR}/resinsight/ApplicationCode/ProjectDataModel/")

set(PROJECTDATAMODEL_SOURCE
# ${RESINSIGHT_APPLICATIONCODE_PROJECTDATAMODEL}RimEclipseResultCase.cpp	
# ${RESINSIGHT_APPLICATIONCODE_PROJECTDATAMODEL}RimWellPath.cpp
# ${RESINSIGHT_APPLICATIONCODE_PROJECTDATAMODEL}RimEclipseCase.cpp
)

set(PROJECTDATAMODEL_HEADERS
${RESINSIGHT_APPLICATIONCODE_PROJECTDATAMODEL}RimWellPath.h
${RESINSIGHT_APPLICATIONCODE_PROJECTDATAMODEL}RimEclipseCase.h
)

# ----------------------------------------------------------------------------------------
# ${CAFPDMCORE_SOURCE}
set(RESINSIGHT_SOURCE
${LIBCORE_SOURCE} 
${LIBGEOMETRY_SOURCE}
${LIBRENDER_SOURCE}
${COMMONCODE_SOURCE} 
${RESERVOIRDATAMODEL_SOURCE} 
${APPLICATION_SOURCE}
${PROJECTDATAMODEL_SOURCE} 
${APPLICATION_TOOLS_SOURCE} 
${APPLICATIONCODE_FILEINTERFACE_SOURCE}
${CAFHEXGRIDINTERSECTIONTOOLS_SOURCE})

set(RESINSIGHT_HEADERS
${LIBCORE_HEADERS} 
${LIBGEOMETRY_HEADERS}
${LIBRENDER_HEADERS}
${CAFPDMCORE_HEADERS}
${COMMONCODE_HEADERS} 
${RESERVOIRDATAMODEL_HEADERS} 
${APPLICATION_HEADERS}
${PROJECTDATAMODEL_HEADERS} 
${APPLICATION_TOOLS_HEADERS} 
${APPLICATIONCODE_FILEINTERFACE_HEADERS}
${CAFHEXGRIDINTERSECTIONTOOLS_HEADERS})